#!/usr/bin/env python3
"""PDFTrail blog generator and validator. Python 3 standard library only.

Commands (run from the repo root or anywhere; paths resolve from this file):

  build.py validate [file.md ...]     check every post (or the named files); exit 1 on failure
  build.py preview <slug>             render one post from drafts/ or posts/ to _blog/preview/<slug>.html
  build.py publish [--now ISO] [--dry-run]
                                      render approved posts whose slot has passed, refresh index/feed/sitemap/llms.txt
  build.py status                     one line per post: slug, slot, state

State model: a post is a Markdown file with front matter. It lives in
_blog/drafts/ (unapproved, gitignored), _blog/posts/ (approved, status: approved),
or _blog/held/ (pulled; ignored). Only posts/ with status: approved and a slot
<= now are ever rendered to blog/<slug>/index.html. Output carries no build
timestamps, so a run with nothing due changes nothing.
"""
import html
import json
import math
import os
import re
import shutil
import sys
from datetime import datetime
from zoneinfo import ZoneInfo

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CONFIG = json.load(open(os.path.join(HERE, "config.json"), encoding="utf-8"))
TZ = ZoneInfo(CONFIG["timezone"])
MARKER = "<!-- generated by _blog/build.py"

REQUIRED = ["title", "description", "date", "time", "kicker", "pillar",
            "primary_keyword", "figure", "figure_alt", "campaign", "faq", "status"]
STATES = {"draft", "approved", "held"}
LIST_KEYS = {"faq", "internal_links"}


def read(path):
    with open(path, encoding="utf-8") as f:
        return f.read()


def write_if_changed(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    if os.path.exists(path) and read(path) == text:
        return False
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    return True


def tpl(name):
    return read(os.path.join(HERE, "templates", name))


def fill(template, mapping):
    out = template
    for k, v in mapping.items():
        out = out.replace("{{" + k + "}}", str(v))
    leftover = re.findall(r"\{\{[a-z_]+\}\}", out)
    if leftover:
        raise RuntimeError("unfilled placeholders: " + ", ".join(sorted(set(leftover))))
    return out


# ---------------------------------------------------------------- front matter

def parse_front_matter(text, path):
    if not text.startswith("---\n"):
        raise ValueError(f"{path}: file must start with a '---' front matter block")
    end = text.find("\n---\n", 4)
    if end < 0:
        raise ValueError(f"{path}: front matter block is not closed")
    head = text[4:end].split("\n")
    body = text[end + 5:]
    meta = {}
    i = 0
    while i < len(head):
        line = head[i]
        i += 1
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        m = re.match(r"^([a-z_]+):\s*(.*)$", line)
        if not m:
            raise ValueError(f"{path}: bad front matter line: {line!r}")
        key, val = m.group(1), m.group(2).strip()
        if key in LIST_KEYS:
            items = []
            while i < len(head) and (head[i].startswith("  ") or not head[i].strip()):
                item_line = head[i]
                i += 1
                if not item_line.strip():
                    continue
                s = item_line.strip()
                if s.startswith("- "):
                    s = s[2:].strip()
                    if key == "faq":
                        if not s.startswith("q:"):
                            raise ValueError(f"{path}: faq item must start with 'q:'")
                        items.append({"q": s[2:].strip(), "a": ""})
                    else:
                        items.append(s)
                elif key == "faq" and s.startswith("a:"):
                    if not items:
                        raise ValueError(f"{path}: 'a:' before any 'q:'")
                    items[-1]["a"] = s[2:].strip()
                else:
                    # continuation of the previous answer line
                    if key == "faq" and items:
                        items[-1]["a"] = (items[-1]["a"] + " " + s).strip()
                    else:
                        raise ValueError(f"{path}: bad list line {item_line!r}")
            meta[key] = items
        else:
            if (val.startswith('"') and val.endswith('"')) or (val.startswith("'") and val.endswith("'")):
                val = val[1:-1]
            meta[key] = val
    return meta, body


# ---------------------------------------------------------------- markdown subset

def inline(text):
    """Escape HTML, then apply the inline subset: code, bold, em, links."""
    s = html.escape(text, quote=False)
    codes = []

    def keep_code(m):
        codes.append("<code>" + m.group(1) + "</code>")
        return "\x00%d\x00" % (len(codes) - 1)

    s = re.sub(r"`([^`]+)`", keep_code, s)
    s = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", s)
    s = re.sub(r"(?<![\w*])\*([^*\n]+)\*(?![\w*])", r"<em>\1</em>", s)

    def link(m):
        label, url = m.group(1), m.group(2)
        if url.startswith("http"):
            return f'<a href="{url}" rel="noopener">{label}</a>'
        return f'<a href="{url}">{label}</a>'

    s = re.sub(r"\[([^\]]+)\]\(([^)\s]+)\)", link, s)
    s = re.sub("\x00(\\d+)\x00", lambda m: codes[int(m.group(1))], s)
    return s


def blocks_of(body):
    blocks, cur = [], []
    for line in body.split("\n"):
        if line.strip() == "":
            if cur:
                blocks.append(cur)
                cur = []
        else:
            cur.append(line.rstrip())
    if cur:
        blocks.append(cur)
    return blocks


FORBIDDEN_LINE = re.compile(r"^(>|\||<|!\[|#\s|####|```|\t|    )")


def convert_body(body, figure_html, errors):
    """Return (standfirst_text, body_html, plain_text, h2s, links, figure_count)."""
    blocks = blocks_of(body)
    if not blocks:
        errors.append("body is empty")
        return "", "", "", [], [], 0
    out, h2s, links, plain = [], [], [], []
    figure_count = 0
    standfirst = None
    seen_first_h2 = False
    inserted_auto_figure = False
    for b in blocks:
        first = b[0]
        for ln in b:
            if FORBIDDEN_LINE.match(ln):
                errors.append(f"unsupported syntax: {ln[:60]!r}")
        if first.strip() == "{{figure}}":
            figure_count += 1
            out.append(figure_html)
            continue
        if first.startswith("## "):
            if seen_first_h2 and "{{figure}}" not in body and not inserted_auto_figure:
                out.append(figure_html)
                inserted_auto_figure = True
                figure_count += 1
            seen_first_h2 = True
            t = " ".join(x.strip() for x in b)[3:].strip()
            h2s.append(t)
            plain.append(t)
            out.append(f"    <h2>{inline(t)}</h2>")
            continue
        if first.startswith("### "):
            t = " ".join(x.strip() for x in b)[4:].strip()
            plain.append(t)
            out.append(f"    <h3>{inline(t)}</h3>")
            continue
        if all(re.match(r"^\s*- ", x) or x.startswith("  ") for x in b) and re.match(r"^- ", first):
            items = _list_items(b, r"^- ")
            plain.extend(items)
            out.append("    <ul>\n" + "\n".join(f"      <li>{inline(i)}</li>" for i in items) + "\n    </ul>")
            continue
        if re.match(r"^\d+\. ", first):
            items = _list_items(b, r"^\d+\. ")
            plain.extend(items)
            out.append("    <ol>\n" + "\n".join(f"      <li>{inline(i)}</li>" for i in items) + "\n    </ol>")
            continue
        text = " ".join(x.strip() for x in b)
        if standfirst is None:
            standfirst = text
            continue
        plain.append(text)
        out.append(f"    <p>{inline(text)}</p>")
    if not inserted_auto_figure and figure_count == 0:
        out.append(figure_html)
        figure_count += 1
    joined = "\n\n".join(out)
    links.extend(re.findall(r'href="([^"]+)"', joined))
    return standfirst or "", joined, "\n".join(plain), h2s, links, figure_count


def _list_items(lines, pat):
    items = []
    for ln in lines:
        if re.match(pat, ln):
            items.append(re.sub(pat, "", ln).strip())
        else:
            items[-1] = items[-1] + " " + ln.strip()
    return items


# ---------------------------------------------------------------- posts

class Post:
    def __init__(self, path, state_dir):
        self.path = path
        self.state_dir = state_dir  # drafts | posts | held
        self.slug = os.path.splitext(os.path.basename(path))[0]
        self.meta, self.body = parse_front_matter(read(path), path)
        self.legacy = False

    @property
    def when(self):
        return datetime.strptime(self.meta["date"] + " " + self.meta["time"], "%Y-%m-%d %H:%M").replace(tzinfo=TZ)

    @property
    def sort_key(self):
        return self.meta["date"] + " " + self.meta["time"]

    @property
    def url(self):
        return f"{CONFIG['site_url']}/blog/{self.slug}/"

    @property
    def rendered_path(self):
        return os.path.join(ROOT, "blog", self.slug, "index.html")

    @property
    def is_live(self):
        return os.path.exists(self.rendered_path)


class Legacy:
    def __init__(self, path):
        self.meta = json.load(open(path, encoding="utf-8"))
        self.slug = self.meta["slug"]
        self.legacy = True
        self.state_dir = "legacy"

    @property
    def sort_key(self):
        return self.meta.get("sort_key") or (self.meta["date"] + " " + self.meta["time"])

    @property
    def url(self):
        return f"{CONFIG['site_url']}/blog/{self.slug}/"

    @property
    def is_live(self):
        return True


def load_posts(dirs=("drafts", "posts", "held")):
    posts = []
    for d in dirs:
        full = os.path.join(HERE, d)
        if not os.path.isdir(full):
            continue
        for name in sorted(os.listdir(full)):
            if name.endswith(".md"):
                posts.append(Post(os.path.join(full, name), d))
    return posts


def load_legacy():
    out = []
    d = os.path.join(HERE, "legacy")
    for name in sorted(os.listdir(d)):
        if name.endswith(".json"):
            out.append(Legacy(os.path.join(d, name)))
    return out


# ---------------------------------------------------------------- rendering

def cta_url(campaign):
    pt = CONFIG.get("app_analytics_pt", "")
    if not pt:
        return CONFIG["app_store_url"]
    return f"{CONFIG['app_store_url']}?pt={pt}&ct={campaign}&mt={CONFIG['app_analytics_mt']}"


def jsonld(obj):
    return json.dumps(obj, ensure_ascii=False, indent=2).replace("</", "<\\/")


def figure_block(meta):
    cap = meta.get("figure_caption", "")
    cap_html = f"\n      <figcaption>{inline(cap)}</figcaption>" if cap else ""
    dims = CONFIG.get("figure_dims", {})
    w, h = dims.get(meta["figure"], dims.get("default", [1400, 875]))
    return ("    <figure>\n"
            f"      <img src=\"/{CONFIG['figure_dir']}/{meta['figure']}\" alt=\"{html.escape(meta['figure_alt'])}\" width=\"{w}\" height=\"{h}\" loading=\"lazy\">"
            f"{cap_html}\n    </figure>")


def related_block(post, everything):
    """Other live posts in the same pillar, hub first, at most five."""
    pillar = post.meta["pillar"]
    hub_slug = CONFIG["pillars"].get(pillar, {}).get("hub")
    cands = [p for p in everything if p.slug != post.slug and p.is_live and p.meta.get("pillar") == pillar]
    cands.sort(key=lambda p: (p.slug != hub_slug, p.sort_key))
    cands = cands[:5]
    if not cands:
        return ""
    items = "\n".join(f'      <li><a href="/blog/{p.slug}/">{html.escape(p.meta["title"])}</a></li>' for p in cands)
    return f"\n    <h2>Related guides</h2>\n    <ul>\n{items}\n    </ul>\n"


def render_post(post, everything, errors=None):
    errors = [] if errors is None else errors
    m = post.meta
    fig = figure_block(m)
    standfirst, body_html, plain, h2s, links, nfig = convert_body(post.body, fig, errors)
    words = len(re.findall(r"\w+", standfirst + " " + plain))
    read_time = m.get("read_time") or max(1, math.ceil(words / 200))
    og_image = m.get("og_image") or os.path.splitext(m["figure"])[0] + ".png"
    if not os.path.exists(os.path.join(ROOT, CONFIG["og_image_dir"], og_image)):
        og_image = CONFIG["default_og_image"]
    article = {
        "@context": "https://schema.org",
        "@type": "Article",
        "headline": m["title"],
        "description": m["description"],
        "author": {"@type": "Person", "name": CONFIG["author"]},
        "publisher": {"@type": "Organization", "name": CONFIG["site_name"], "url": CONFIG["site_url"] + "/"},
        "datePublished": m["date"],
        "dateModified": m.get("updated") or m["date"],
        "image": [f"{CONFIG['site_url']}/{CONFIG['og_image_dir']}/{og_image}"],
        "mainEntityOfPage": post.url,
    }
    faq = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [
            {"@type": "Question", "name": q["q"],
             "acceptedAnswer": {"@type": "Answer", "text": q["a"]}}
            for q in m.get("faq", [])
        ],
    }
    faq_html = "\n".join(
        f"      <details>\n        <summary>{inline(q['q'])}</summary>\n        <p>{inline(q['a'])}</p>\n      </details>"
        for q in m.get("faq", []))
    page = fill(tpl("post.html"), {
        "slug": post.slug,
        "site_url": CONFIG["site_url"],
        "seo_title": html.escape(m.get("seo_title") or m["title"], quote=False),
        "title": html.escape(m["title"], quote=True),
        "description": html.escape(m["description"], quote=True),
        "og_image_dir": CONFIG["og_image_dir"],
        "og_image": og_image,
        "article_jsonld": jsonld(article),
        "faq_jsonld": jsonld(faq),
        "cta_url": html.escape(cta_url(m["campaign"]), quote=True),
        "cta_label": html.escape(m.get("cta_label") or CONFIG["default_cta_label"]),
        "kicker": html.escape(m["kicker"]),
        "date": m["date"],
        "author": CONFIG["author"],
        "standfirst": inline(standfirst),
        "read_time": read_time,
        "body_html": body_html,
        "faq_html": faq_html,
        "related_html": related_block(post, everything),
    })
    info = {"words": words, "standfirst": standfirst, "plain": plain, "h2s": h2s,
            "links": links, "figures": nfig, "faq_n": len(m.get("faq", []))}
    return page, info


# ---------------------------------------------------------------- validation

def validate_post(post, everything, live_slugs):
    m, errs, warns = post.meta, [], []
    for k in REQUIRED:
        if k not in m or (isinstance(m[k], str) and not m[k].strip()) or (isinstance(m[k], list) and not m[k]):
            errs.append(f"missing required field '{k}'")
    if errs:
        return errs, warns
    if m["status"] not in STATES:
        errs.append(f"status must be one of {sorted(STATES)}")
    if post.state_dir == "posts" and m["status"] != "approved":
        errs.append("a file in posts/ must have status: approved")
    if post.state_dir == "drafts" and m["status"] == "approved":
        errs.append("an approved post must be moved to posts/")
    try:
        post.when
    except ValueError:
        errs.append("date/time must be YYYY-MM-DD and HH:MM")
    if not re.match(r"^[a-z0-9]+(-[a-z0-9]+)*$", post.slug):
        errs.append("slug (file name) must be lowercase words joined by hyphens")
    kw = m["primary_keyword"].lower()
    if len(m["title"]) > 60:
        errs.append(f"title is {len(m['title'])} chars (max 60)")
    if kw not in m["title"].lower():
        warns.append("primary keyword is not in the title verbatim")
    d = len(m["description"])
    if not 70 <= d <= 155:
        errs.append(f"description is {d} chars (70-155)")
    if kw not in m["description"].lower():
        warns.append("primary keyword is not in the description verbatim")
    if m["kicker"] not in CONFIG["kickers"]:
        errs.append(f"kicker must be one of {CONFIG['kickers']}")
    if m["pillar"] not in CONFIG["pillars"]:
        errs.append(f"pillar must be one of {sorted(CONFIG['pillars'])}")
    if not os.path.exists(os.path.join(ROOT, CONFIG["figure_dir"], m["figure"])):
        errs.append(f"figure {m['figure']} not found in {CONFIG['figure_dir']}")
    if len(m["figure_alt"]) < 40:
        errs.append("figure_alt must be at least 40 chars")
    if kw not in m["figure_alt"].lower():
        warns.append("primary keyword is not in figure_alt")
    if not re.match(r"^[a-z0-9-]{3,40}$", m["campaign"]):
        errs.append("campaign must match [a-z0-9-]{3,40}")
    faq = m.get("faq", [])
    if not 3 <= len(faq) <= 6:
        errs.append(f"faq has {len(faq)} items (3-6)")
    for q in faq:
        if not q.get("q") or not q.get("a"):
            errs.append("every faq item needs q and a")
    if not any(re.search(r"on your mac|on-device|on device", q.get("a", "").lower()) for q in faq):
        warns.append("no FAQ answer says 'on your Mac' or 'on-device'")
    # uniqueness
    for other in everything:
        if other.slug == post.slug:
            continue
        if other.meta.get("primary_keyword", "").lower() == kw:
            errs.append(f"primary keyword duplicates {other.slug}")
        if not other.legacy and other.meta.get("campaign") == m["campaign"]:
            errs.append(f"campaign token duplicates {other.slug}")
        if not other.legacy and other.state_dir != "held" and other.meta.get("date") == m["date"] and other.meta.get("time") == m["time"]:
            errs.append(f"same slot as {other.slug}")
    # body
    render_errs = []
    page, info = render_post(post, everything, render_errs)
    errs.extend(render_errs)
    if not CONFIG["word_min"] <= info["words"] <= CONFIG["word_max"]:
        errs.append(f"body has {info['words']} words ({CONFIG['word_min']}-{CONFIG['word_max']}, FAQ excluded)")
    if info["figures"] != 1:
        errs.append(f"{info['figures']} figures (exactly one {{{{figure}}}} or none for auto-placement)")
    if not 3 <= len(info["h2s"]) <= 7:
        errs.append(f"{len(info['h2s'])} H2 sections (3-7)")
    first100 = " ".join(re.findall(r"\w+", (info["standfirst"] + " " + info["plain"]).lower())[:100])
    if kw not in first100:
        warns.append("primary keyword is not in the first 100 words")
    if not any(kw in h.lower() for h in info["h2s"]):
        warns.append("primary keyword is not in any H2")
    text_all = info["standfirst"] + "\n" + info["plain"] + "\n" + " ".join(q["a"] for q in faq)
    if "pdftrail is my app" not in text_all.lower() and "it's my app" not in text_all.lower() and "my app" not in text_all.lower():
        errs.append("disclosure missing: say that PDFTrail is my app")
    for pat in CONFIG["banned_patterns"]:
        hit = re.search(pat, text_all + "\n" + m["title"] + "\n" + m["description"], re.I)
        if hit:
            errs.append(f"banned phrase: {hit.group(0)!r}")
    # links
    internal = [l for l in info["links"] if l.startswith("/")]
    external = [l for l in info["links"] if l.startswith("http")]
    ok_static = {"/", "/blog/", "/support.html", "/privacy.html"}
    for l in internal:
        if l in ok_static:
            continue
        mm = re.match(r"^/blog/([a-z0-9-]+)/$", l)
        if not mm:
            errs.append(f"bad internal link {l}")
            continue
        target = mm.group(1)
        tp = next((p for p in everything if p.slug == target), None)
        if target in live_slugs:
            continue
        if tp is None or tp.state_dir == "held":
            errs.append(f"internal link to unknown or held post {target}")
        elif tp.sort_key > post.sort_key:
            errs.append(f"internal link to {target}, which is scheduled after this post")
    n_int = len([l for l in internal if l.startswith("/blog/") and l != "/blog/"])
    if n_int < 2:
        errs.append(f"{n_int} internal /blog/ links (need 2-3)")
    if n_int > 4:
        warns.append(f"{n_int} internal links (2-3 is the target)")
    cited = 0
    for l in external:
        host_path = re.sub(r"^https?://(www\.)?", "", l)
        if any(host_path.startswith(dom) for dom in CONFIG["citation_domains"]):
            cited += 1
        elif "apps.apple.com" in l:
            errs.append("do not put App Store links in the body; the template adds the CTA")
        else:
            errs.append(f"external link domain not on the allow-list: {l}")
    if cited < 1:
        errs.append("no external citation from the allow-list")
    # sentence length
    sentences = re.split(r"(?<=[.!?])\s+|\n", info["standfirst"] + "\n" + info["plain"])
    lens = [len(re.findall(r"\w+", s)) for s in sentences if s.strip()]
    if lens:
        avg = sum(lens) / len(lens)
        if avg > CONFIG["sentence_warn"]:
            warns.append(f"average sentence length {avg:.1f} words (target <= {CONFIG['sentence_warn']})")
        longest = max(lens)
        if longest > CONFIG["sentence_fail"]:
            errs.append(f"a sentence has {longest} words (max {CONFIG['sentence_fail']})")
    if kw and len(re.findall(re.escape(kw), text_all.lower())) > 8:
        warns.append("primary keyword used more than 8 times")
    return errs, warns


def shingle_check(posts):
    """Fail when two posts share any run of N words (FAQ excluded)."""
    n = CONFIG["shingle_words"]
    seen = {}
    errs = []
    for p in posts:
        _, info = render_post(p, posts, [])
        text = (info["standfirst"] + " " + info["plain"]).lower()
        for ex in CONFIG.get("shingle_exempt", []):
            text = text.replace(ex.lower(), " | ")
        words = re.findall(r"\w+", text)
        mine = set()
        for i in range(len(words) - n + 1):
            sh = " ".join(words[i:i + n])
            if sh in mine:
                continue
            mine.add(sh)
            if sh in seen and seen[sh] != p.slug:
                errs.append(f"{p.slug} shares {n} words with {seen[sh]}: '{sh[:50]}...'")
                break
            seen.setdefault(sh, p.slug)
    return errs


def cmd_validate(args):
    posts = load_posts()
    legacy = load_legacy()
    everything = posts + legacy
    live = {p.slug for p in everything if p.is_live}
    targets = posts
    if args:
        wanted = {os.path.splitext(os.path.basename(a))[0] for a in args}
        targets = [p for p in posts if p.slug in wanted]
    failed = 0
    for p in targets:
        if p.state_dir == "held":
            continue
        errs, warns = validate_post(p, everything, live)
        for w in warns:
            print(f"WARN  {p.slug}: {w}")
        for e in errs:
            print(f"FAIL  {p.slug}: {e}")
        if errs:
            failed += 1
        else:
            print(f"OK    {p.slug}")
    for e in shingle_check([p for p in targets if p.state_dir != "held"]):
        print("FAIL  " + e)
        failed += 1
    print(f"{len(targets)} checked, {failed} failed")
    return 1 if failed else 0


# ---------------------------------------------------------------- site files

def xml_escape(s):
    return html.escape(s, quote=False)


def rfc822(meta):
    dt = datetime.strptime(meta["date"] + " " + meta["time"], "%Y-%m-%d %H:%M").replace(tzinfo=TZ)
    return dt.strftime("%a, %d %b %Y %H:%M:%S %z")


def write_site_files(live_items):
    """live_items: legacy + rendered posts. Returns list of changed paths."""
    changed = []
    ordered = sorted(live_items, key=lambda p: p.sort_key, reverse=True)
    cards = "\n".join(
        f'    <a class="post-card" href="/blog/{p.slug}/">\n'
        f'      <p class="pc-date">{p.meta["date"]} · {html.escape(p.meta["kicker"])}</p>\n'
        f'      <h2>{html.escape(p.meta["title"], quote=False)}</h2>\n'
        f'      <p>{html.escape(p.meta.get("summary") or p.meta["description"], quote=False)}</p>\n'
        f'    </a>' for p in ordered)
    if write_if_changed(os.path.join(ROOT, "blog", "index.html"), fill(tpl("index.html"), {"cards": cards})):
        changed.append("blog/index.html")
    items = "\n".join(
        "  <item>\n"
        f"    <title>{xml_escape(p.meta['title'])}</title>\n"
        f"    <link>{p.url}</link>\n"
        f"    <guid>{p.url}</guid>\n"
        f"    <pubDate>{rfc822(p.meta)}</pubDate>\n"
        f"    <description>{xml_escape(p.meta.get('feed_summary') or p.meta.get('summary') or p.meta['description'])}</description>\n"
        "  </item>" for p in ordered)
    if write_if_changed(os.path.join(ROOT, "blog", "feed.xml"), fill(tpl("feed.xml"), {"items": items})):
        changed.append("blog/feed.xml")
    lm = CONFIG["sitemap_static_lastmod"]
    urls = [f"  <url><loc>{CONFIG['site_url']}{u}</loc><lastmod>{lm}</lastmod></url>" for u in CONFIG["sitemap_before"]]
    for p in sorted(live_items, key=lambda p: p.slug):
        urls.append(f"  <url><loc>{p.url}</loc><lastmod>{p.meta.get('updated') or p.meta['date']}</lastmod></url>")
    urls += [f"  <url><loc>{CONFIG['site_url']}{u}</loc><lastmod>{lm}</lastmod></url>" for u in CONFIG["sitemap_after"]]
    if write_if_changed(os.path.join(ROOT, "sitemap.xml"), fill(tpl("sitemap.xml"), {"urls": "\n".join(urls)})):
        changed.append("sitemap.xml")
    guides, notes = [], []
    for p in ordered:
        section = p.meta.get("llms_section") or ("notes" if p.meta["kicker"] in ("Engine notes", "Release notes") else "guides")
        blurb = p.meta.get("llms_blurb") or p.meta["description"]
        line = f"- [{p.meta['title']}]({p.url}): {blurb}"
        (guides if section == "guides" else notes).append((p, line))
    # hubs first inside guides
    hubs = {v["hub"] for v in CONFIG["pillars"].values()}
    guides.sort(key=lambda t: (t[0].slug not in hubs, ordered.index(t[0])))
    if write_if_changed(os.path.join(ROOT, "llms.txt"), fill(tpl("llms.txt"), {
            "guides": "\n".join(l for _, l in guides), "notes": "\n".join(l for _, l in notes)})):
        changed.append("llms.txt")
    return changed


# ---------------------------------------------------------------- commands

def cmd_preview(args):
    if not args:
        print("usage: build.py preview <slug>")
        return 2
    slug = args[0]
    posts = load_posts()
    legacy = load_legacy()
    post = next((p for p in posts if p.slug == slug), None)
    if post is None:
        print(f"no post named {slug} in drafts/, posts/ or held/")
        return 1
    errs = []
    page, info = render_post(post, posts + legacy, errs)
    out = os.path.join(HERE, "preview", slug + ".html")
    # previews use root-relative assets; rewrite to absolute so the file opens standalone
    page = page.replace('href="/assets/', f'href="{CONFIG["site_url"]}/assets/').replace('src="/assets/', f'src="{CONFIG["site_url"]}/assets/')
    write_if_changed(out, page)
    v_errs, v_warns = validate_post(post, posts + legacy, {p.slug for p in posts + legacy if p.is_live})
    for w in v_warns:
        print("WARN  " + w)
    for e in v_errs:
        print("FAIL  " + e)
    print(f"{out}  ({info['words']} words, {len(info['h2s'])} H2, {info['faq_n']} FAQ)")
    return 0


def cmd_publish(args):
    now = datetime.now(TZ)
    dry = "--dry-run" in args
    if "--now" in args:
        now = datetime.fromisoformat(args[args.index("--now") + 1])
        if now.tzinfo is None:
            now = now.replace(tzinfo=TZ)
    posts = load_posts()
    legacy = load_legacy()
    everything = posts + legacy
    approved = [p for p in posts if p.state_dir == "posts" and p.meta.get("status") == "approved"]
    due = [p for p in approved if p.when <= now]
    live_slugs = {p.slug for p in everything if p.is_live}
    # validate everything that will be live after this run
    failed = False
    for p in due:
        errs, _ = validate_post(p, everything, live_slugs | {d.slug for d in due})
        for e in errs:
            print(f"FAIL  {p.slug}: {e}")
            failed = True
    if failed:
        print("publish aborted: validation failed")
        return 1
    newly = [p for p in due if not p.is_live]
    changed = []
    if not dry:
        # render every due post (re-renders refresh Related guides on older posts)
        for p in due:
            page, _ = render_post(p, everything)
            if write_if_changed(p.rendered_path, page):
                changed.append(f"blog/{p.slug}/index.html")
        # prune generated dirs whose .md is gone
        keep = {p.slug for p in due} | {l.slug for l in legacy}
        blog_dir = os.path.join(ROOT, "blog")
        for name in os.listdir(blog_dir):
            d = os.path.join(blog_dir, name)
            idx = os.path.join(d, "index.html")
            if os.path.isdir(d) and name not in keep and os.path.exists(idx) and MARKER in read(idx)[:400]:
                shutil.rmtree(d)
                changed.append(f"blog/{name}/ (removed)")
        changed += write_site_files(legacy + due)
    print(f"now={now.isoformat()} approved={len(approved)} due={len(due)} new={len(newly)}")
    for p in newly:
        print(f"PUBLISHED {p.slug} -> {p.url}")
    if changed:
        print("changed: " + ", ".join(changed))
    else:
        print("nothing due")
    return 0


def cmd_status(args):
    now = datetime.now(TZ)
    rows = []
    for p in load_posts():
        st = p.meta.get("status", "?")
        if p.state_dir == "held":
            state = "held"
        elif p.is_live:
            state = "LIVE"
        elif st == "approved" and p.when <= now:
            state = "DUE (approved, not yet published)"
        elif st == "approved":
            state = "queued"
        else:
            state = "draft"
        rows.append((p.sort_key, p.slug, p.meta.get("pillar", "?"), state))
    for l in load_legacy():
        rows.append((l.sort_key, l.slug, l.meta.get("pillar", "?"), "LIVE (legacy)"))
    rows.sort()
    for k, slug, pillar, state in rows:
        print(f"{k}  {pillar:3}  {slug:45} {state}")
    return 0


def main(argv):
    if len(argv) < 2:
        print(__doc__)
        return 2
    cmd, args = argv[1], argv[2:]
    if cmd == "validate":
        return cmd_validate(args)
    if cmd == "preview":
        return cmd_preview(args)
    if cmd == "publish":
        return cmd_publish(args)
    if cmd == "status":
        return cmd_status(args)
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
